version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - mynetwork

# docker run --file ./frontend/Dockerfile --name frontend -p 3000:3000 
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      MONGODB_URL: "mongodb://mongo:27017/paws1"
    networks:
      - mynetwork

    depends_on:
      - mongo

  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge