# Use a node base image
FROM node:16

# MongoDB version to install
ARG MONGO_VERSION=4.4

# Set the working directory in the container
WORKDIR /app

# Install MongoDB
RUN apt-get update && apt-get install -y gnupg wget && \
    wget -qO - https://www.mongodb.org/static/pgp/server-${MONGO_VERSION}.asc | apt-key add - && \
    echo "deb http://repo.mongodb.org/apt/debian buster/mongodb-org/${MONGO_VERSION} main" | tee /etc/apt/sources.list.d/mongodb-org-${MONGO_VERSION}.list && \
    apt-get update && \
    apt-get install -y mongodb-org && \
    mkdir -p /data/db

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Install nodemon globally
RUN npm install -g nodemon

# Copy the rest of your app's source code
COPY . .

# Your application's default port, adjust if it's different
EXPOSE 8000

# MongoDB port
EXPOSE 27017

# Custom script to start MongoDB and then your Node.js app
COPY docker-entrypoint.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

# Command to run your application and MongoDB
CMD ["docker-entrypoint.sh"]
